id = "bml"
name = "BML"
description = "BML (Bare Metal Language) support for Zed. Provides syntax highlighting, LSP integration, and more for embedded systems development."
version = "0.1.0"
schema_version = 1
authors = ["BML Contributors"]
repository = "https://github.com/tralamazza/bml-zed"

[grammars.bml]
repository = "https://github.com/tralamazza/bml-zed"
path = "tree-sitter-bml"
rev = "8ecf0c18fb66a334d01602f48462a781b89c01c1"

[language_servers.bml-lsp]
name = "bml-lsp"
languages = ["BML"]
