name = "BML"
grammar = "bml"
path_suffixes = ["bml"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
tab_size = 4
hard_tabs = false
autoclose_before = ";:.,=}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
debuggers = ["GDB"]
