fn main() {
    // parser.c is generated by `tree-sitter generate`
    let parser_c = "src/parser.c";
    if std::path::Path::new(parser_c).exists() {
        let mut build = cc::Build::new();
        build.file(parser_c);
        // scanner.c provides the external tokens (nested block comments, asm body)
        let scanner_c = "src/scanner.c";
        if std::path::Path::new(scanner_c).exists() {
            build.file(scanner_c);
        }
        build.compile("tree-sitter-bml");
    }
}
