fn main() {
    // parser.c is generated by `tree-sitter generate`
    let parser_c = "src/parser.c";
    if std::path::Path::new(parser_c).exists() {
        cc::Build::new()
            .file(parser_c)
            .compile("tree-sitter-bml");
    }
}
